from .ad_door import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .rp import NODE_CLASS_MAPPINGS as RHAPI_NODE_CLASS_MAPPINGS
from .rp import NODE_DISPLAY_NAME_MAPPINGS as RHAPI_NODE_DISPLAY_NAME_MAPPINGS
from .nodes import NODE_CLASS_MAPPINGS as NODES_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_NAME_MAPPINGS

# Update mappings to include RHAPI mappings and nodes mappings
NODE_CLASS_MAPPINGS.update(RHAPI_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NODES_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RHAPI_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NODES_DISPLAY_NAME_MAPPINGS)

# WEB_DIRECTORY = "./web"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
