from .classes.AD_BatchImageLoadFromDir import AD_BatchImageLoadFromDir, NODE_CLASS_MAPPINGS as BATCH_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_DISPLAY_MAPPINGS
from .classes.AD_DeleteLocalAny import AD_DeleteLocalAny, NODE_CLASS_MAPPINGS as DELETE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DELETE_DISPLAY_MAPPINGS
from .classes.AD_TextListToString import AD_TextListToString, NODE_CLASS_MAPPINGS as TEXT_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS
from .classes.AD_AnyFileList import AD_AnyFileList, NODE_CLASS_MAPPINGS as ANY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ANY_DISPLAY_MAPPINGS
from .classes.AD_ZipSave import AD_ZipSave, NODE_CLASS_MAPPINGS as ZIP_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ZIP_DISPLAY_MAPPINGS
from .classes.AD_ImageSaver import AD_ImageSaver, NODE_CLASS_MAPPINGS as IMAGE_SAVER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SAVER_DISPLAY_MAPPINGS
from .classes.AD_FluxTrainStepMath import AD_FluxTrainStepMath, NODE_CLASS_MAPPINGS as FLUX_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLUX_DISPLAY_MAPPINGS
from .classes.AD_TextSaver import AD_TextSaver, NODE_CLASS_MAPPINGS as TEXT_SAVER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_SAVER_DISPLAY_MAPPINGS
from .classes.AD_PromptReplace import AD_PromptReplace, NODE_CLASS_MAPPINGS as PROMPT_REPLACE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_REPLACE_DISPLAY_MAPPINGS
from .classes.AD_HFDownload import AD_HFDownload, NODE_CLASS_MAPPINGS as HF_DOWNLOAD_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as HF_DOWNLOAD_DISPLAY_MAPPINGS
from .classes.AD_ImageColorFilter import AD_ImageColorFilter, NODE_CLASS_MAPPINGS as IMAGE_COLOR_FILTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_COLOR_FILTER_DISPLAY_MAPPINGS
from .classes.AD_CSVReader import AD_CSVReader, NODE_CLASS_MAPPINGS as CSV_READER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CSV_READER_DISPLAY_MAPPINGS
from .classes.AD_CSVPromptStyler import AD_CSVPromptStyler, NODE_CLASS_MAPPINGS as CSV_PROMPT_STYLER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CSV_PROMPT_STYLER_DISPLAY_MAPPINGS
from .classes.AD_TxtToCSVCombiner import AD_TxtToCSVCombiner, NODE_CLASS_MAPPINGS as TXT_TO_CSV_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TXT_TO_CSV_DISPLAY_MAPPINGS
from .classes.AD_CSVTranslator import AD_CSVTranslator, NODE_CLASS_MAPPINGS as CSV_TRANSLATOR_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CSV_TRANSLATOR_DISPLAY_MAPPINGS
from .classes.AD_LoadImageAdvanced import AD_LoadImageAdvanced, NODE_CLASS_MAPPINGS as LOAD_IMAGE_ADVANCED_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_ADVANCED_DISPLAY_MAPPINGS
from .classes.AD_ImageDrawRectangleSimple import AD_ImageDrawRectangleSimple, NODE_CLASS_MAPPINGS as DRAW_RECTANGLE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DRAW_RECTANGLE_DISPLAY_MAPPINGS
from .classes.AD_ImageIndexer import AD_ImageIndexer, NODE_CLASS_MAPPINGS as IMAGE_INDEXER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_INDEXER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **BATCH_CLASS_MAPPINGS,
    **DELETE_CLASS_MAPPINGS,
    **TEXT_CLASS_MAPPINGS,
    **ANY_CLASS_MAPPINGS,
    **ZIP_CLASS_MAPPINGS,
    **IMAGE_SAVER_CLASS_MAPPINGS,
    **FLUX_CLASS_MAPPINGS,
    **TEXT_SAVER_CLASS_MAPPINGS,
    **PROMPT_REPLACE_CLASS_MAPPINGS,
    **HF_DOWNLOAD_CLASS_MAPPINGS,
    **IMAGE_COLOR_FILTER_CLASS_MAPPINGS,
    **CSV_READER_CLASS_MAPPINGS,
    **CSV_PROMPT_STYLER_CLASS_MAPPINGS,
    **TXT_TO_CSV_CLASS_MAPPINGS,
    **CSV_TRANSLATOR_CLASS_MAPPINGS,
    **LOAD_IMAGE_ADVANCED_CLASS_MAPPINGS,
    **DRAW_RECTANGLE_CLASS_MAPPINGS,
    **IMAGE_INDEXER_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BATCH_DISPLAY_MAPPINGS,
    **DELETE_DISPLAY_MAPPINGS,
    **TEXT_DISPLAY_MAPPINGS,
    **ANY_DISPLAY_MAPPINGS,
    **ZIP_DISPLAY_MAPPINGS,
    **IMAGE_SAVER_DISPLAY_MAPPINGS,
    **FLUX_DISPLAY_MAPPINGS,
    **TEXT_SAVER_DISPLAY_MAPPINGS,
    **PROMPT_REPLACE_DISPLAY_MAPPINGS,
    **HF_DOWNLOAD_DISPLAY_MAPPINGS,
    **IMAGE_COLOR_FILTER_DISPLAY_MAPPINGS,
    **CSV_READER_DISPLAY_MAPPINGS,
    **CSV_PROMPT_STYLER_DISPLAY_MAPPINGS,
    **TXT_TO_CSV_DISPLAY_MAPPINGS,
    **CSV_TRANSLATOR_DISPLAY_MAPPINGS,
    **LOAD_IMAGE_ADVANCED_DISPLAY_MAPPINGS,
    **DRAW_RECTANGLE_DISPLAY_MAPPINGS,
    **IMAGE_INDEXER_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

