[project]
name = "comfyui-addoor"
description = "A collection of batch operation toolkits suitable for ComfyUI"
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["# Core dependencies", "numpy>=1.21.0", "Pillow>=9.0.0", "torch>=1.9.0", "torchvision>=0.10.0", "# Image processing", "scikit-image>=0.19.0", "opencv-python>=4.5.0", "matplotlib>=3.3.0", "scipy>=1.7.0", "# File handling", "zipfile36>=0.1.3", "# Hugging Face integration", "huggingface_hub[cli,torch]>=0.10.0", "# ComfyUI specific (you may need to adjust these based on ComfyUI's requirements)", "gradio>=3.0.0", "# Optional: for progress bars (if used in your project)", "tqdm>=4.62.0", "# Optional: for web requests (if used in your project)", "requests>=2.31.0", "pycryptodome>=3.15.0", "configparser>=5.0.0", "filelock>=3.0.12"]

[project.urls]
Repository = "https://github.com/Eagle-CN/ComfyUI-Addoor"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-Addoor"
Icon = ""
